node {
  name: "tracker"
  calculator: "box_tracker"
  input_stream: "detection_stream"
  input_stream: "image_stream_decode"
  input_stream: "detect_interval"
  output_stream: "tracks_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxTrackerOptions]: {
      speed_buffer_max_size: 0
      max_keep_alive: 0
      min_hits: 1
      keep_tracker_iou_thresh: 0
      bind_obj_iou_thresh: 0
      affinity_threshold: 0  
      shape_weight: 1
      position_weight: 1
      appearnace_weight: 1
      shape_dist_max: 1
      position_dist_max: 1
      use_exp_cost: false
      tracker_type: ""
      min_object_area_th: 0
    }
  }
}