control_port: 51881
graph_input: "graph_input1"

node {
  name: "img_stream"
  calculator: "image_stream"
  graph_input: "graph_input1"
  output_stream: "image_stream_1080p"
  output_stream: "decode_vid_info_side_packet"
  output_stream_attributes: {
    name: "image_stream_1080p"
    capacity: 128
  }
  node_options: {
    [type.googleapis.com/aup.avaf.ImageStreamOptions]: {
      playback_fps: 10000
      directory: "/home/chengyou/VMSS/images/one_img/416_416/"
      width: 416
      height: 416
      loop_over: true
      pool_size: 128
      preload_images: true
    }
  }
}

node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "image_stream_1080p"
  output_stream: "detections_stream"
  output_stream: "detect_interval_dangling"
  ml_model_kernel_name: "yolov3_voc_tf"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "YoloV3"
      need_preprocess: false
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 8
      detection_threads: 8
      return_frames_inorder: false 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 500
      total_classes: 20
      default_confidence_threshold: 0.3
      mean: {
        r: 0
        g: 0
        b: 0
      }
      scale: {
        ch1: 0.00390625
        ch2: 0.00390625
        ch3: 0.00390625
      }
    }
  }
}

statistics_collector: {
  target_file: "/tmp/stats/yolov3_voc_tf_throughput.json"
  throughput_stream_name: "detections_stream"
  throughput_ignore_initial_packets_count: 1000
}

node {
    name: "statistics_reader"
    calculator: "statistics_reader"
    output_stream: "json_notification"
    node_options: {
    [type.googleapis.com/aup.avaf.StatisticsReaderOptions]: {
        interval_us: 1000000
        input_path: "/tmp/stats/yolov3_voc_tf_throughput.json"
        loop_over: true
        input_type: FILE
        only_send_throughput: true
    }
  }
}

node {
    name: "notification_web"
    calculator: "notification_web"
    vendor: "Aupera"
    input_stream: "json_notification"
    node_options: {
    [type.googleapis.com/aup.avaf.NotificationWebOptions]: {
        notification_url: ""
        notification_q_size: 1
        protocol_type: HTTP
    }
  }
}