node {
  name: "mux_node2"
  calculator: "stream_mux"
  input_stream: "packet_stream_encode2"
  input_stream: "codec_context_stream2"
  graph_output: "graph_output2"
  node_options: {
    [type.googleapis.com/aup.avaf.StreamMuxOptions]: {
     mux: {
       rtsp_transport: "tcp"
       auto_reconnect: true
     }
    }
  }
}