node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "image_stream_decode"
  output_stream: "detections_stream"
  output_stream: "detect_interval"
  ml_model_kernel_name: "yolov3_adas_pruned_0_9"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "YoloV3"
      need_preprocess: true
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_frames_inorder: true 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 30
      total_classes: 3
      default_confidence_threshold: 0.3
      mean: {
        r: 0
        g: 0
        b: 0
      }
      scale: {
        ch1: 0.00390625
        ch2: 0.00390625
        ch3: 0.00390625
      }
    }
  }
}