node {
  name: "vfilter_node1"
  calculator: "ff_vfilter"
  input_stream: "image_stream_viz1"
  input_stream: "video_stream_info_decode1"
  output_stream: "image_stream_vfilter1"
  output_stream: "video_stream_info_vfilter1"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoFilterOptions]: {
      roi_x: 0
      roi_y: 0
      roi_w: 0
      roi_h: 0
      opixfmt: PIXFMT_I420
      ow: 1280
      oh: 720
      ofps: 25
    }
  }
}