node {
  name: "classifier"
  calculator: "box_classifier"
  input_stream: "detections_stream"
  input_stream: "image_stream_decode"
  output_stream: "classification_stream"
  ml_model_kernel_name: ""
  node_options: {
    [type.googleapis.com/aup.avaf.BoxClassifierOptions]: {
      classifier_type: ""
      need_preprocess: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_in_order: false
      classification_threads: 1
      force_batch_size: false
      batch_collection_timeout_ms: 0
      use_detections: false
      log_performance: false
      max_classification_lib_q_size: 32
      max_frame_cache_size: 32
    }
  }
}