node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "imgStream1080p"
  output_stream: "detectionsStream"
  output_stream: "detect_interval"
  stream_sync: {
    drop_strategy: DROP_INCOMPLETE_PACKETS
    timeout_ms: 5000
  }
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "YoloV2"
      kernel_name: "yolov2_voc"      
      need_preprocess: true
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_frames_inorder: true 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 30
      mean: {
        r: 0
        g: 0
        b: 0
      }
      scale: {
        ch1: 0.00390625
        ch2: 0.00390625
        ch3: 0.00390625
      }
      label_confidence: {
        label: 0
        confidence: 0.3
      }
      label_confidence: {
        label: 1
        confidence: 0.3
      }
      label_confidence: {
        label: 2
        confidence: 0.3
      }
      label_confidence: {
        label: 3
        confidence: 0.3
      }
      label_confidence: {
        label: 4
        confidence: 0.3
      }
      label_confidence: {
        label: 3
        confidence: 0.3
      }
      label_confidence: {
        label: 6
        confidence: 0.3
      }
      label_confidence: {
        label: 7
        confidence: 0.3
      }
      label_confidence: {
        label: 8
        confidence: 0.3
      }
      label_confidence: {
        label: 9
        confidence: 0.3
      }
      label_confidence: {
        label: 10
        confidence: 0.3
      }
      label_confidence: {
        label: 11
        confidence: 0.3
      }
      label_confidence: {
        label: 12
        confidence: 0.3
      }
      label_confidence: {
        label: 13
        confidence: 0.3
      }
      label_confidence: {
        label: 14
        confidence: 0.3
      }
      label_confidence: {
        label: 15
        confidence: 0.3
      }
      label_confidence: {
        label: 16
        confidence: 0.3
      }
      label_confidence: {
        label: 17
        confidence: 0.3
      }
      label_confidence: {
        label: 18
        confidence: 0.3
      }
      label_confidence: {
        label: 19
        confidence: 0.3
      }
      inter_class_nms: {
        labels: 0
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 1
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 2
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 3
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 4
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 5
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 6
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 7
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 8
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 9
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 10
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 11
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 12
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 13
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 14
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 15
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 16
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 17
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 18
        threshold: 0.45
      }
      inter_class_nms: {
        labels: 19
        threshold: 0.45
      }
    }
  }
}